#!/bin/bash

echo "=== Update Camera Configuration ==="
echo ""
echo "The API Gateway is now working with the unrestricted key."
echo ""
echo "Current working configuration:"
echo "- API Gateway URL: https://anava-gateway-2gvbe0bn.uc.gateway.dev"
echo "- API Key (unrestricted): AIzaSyCprB_r1KDwAMBteqjh2hfdlzzgPjtxvWY"
echo ""
echo "To update the camera:"
echo ""
echo "1. Open the Electron app"
echo "2. Go to the Configuration tab"
echo "3. The API Key shown will be the old restricted one"
echo "4. Click 'Send to Camera' and enter the camera IP"
echo ""
echo "The camera will receive the old API key, but we need to update it."
echo ""
echo "Temporary fix - manually update the API key on the camera:"
echo "- SSH into the camera"
echo "- Update ParamManager with the new API key"
echo ""
echo "Permanent fix - update the Terraform outputs with the correct API key"