apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@anava-vision.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@anava-vision.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anava-vision-tls
  namespace: anava-vision
spec:
  secretName: anava-vision-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: anava-vision.com
  dnsNames:
  - anava-vision.com
  - "*.anava-vision.com"
  - api.anava-vision.com
  - ws.anava-vision.com
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  subject:
    organizations:
    - Anava Vision
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - digital signature
  - key encipherment