name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'web-service/cloud-run/**'
  workflow_dispatch:

env:
  PROJECT_ID: anava-ai
  SERVICE: anava-deploy
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Enable APIs
      run: |
        gcloud services enable \
          cloudbuild.googleapis.com \
          run.googleapis.com \
          cloudfunctions.googleapis.com \
          firebase.googleapis.com \
          --project=$PROJECT_ID

    - name: Deploy to Cloud Run
      run: |
        cd web-service/cloud-run
        gcloud run deploy $SERVICE \
          --source . \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "GOOGLE_CLOUD_PROJECT=$PROJECT_ID,REDIS_HOST=10.150.87.59,REDIRECT_URI=https://anava-deploy-392865621461.us-central1.run.app/callback" \
          --vpc-connector anava-deploy-connector \
          --vpc-egress private-ranges-only \
          --memory 2Gi \
          --cpu 2 \
          --timeout 3600 \
          --max-instances 10 \
          --project $PROJECT_ID

    - name: Verify Deployment
      run: |
        URL=$(gcloud run services describe $SERVICE --region $REGION --format 'value(status.url)')
        curl -f $URL/health || exit 1